const canvas=document.querySelector('#globe'),ctx=canvas.getContext('2d');
const places=[{name:'Raa Atoll',lat:5.67,lon:72.93,status:'ExploraciÃ³n realizada en este destino.'},{name:'Boa Vista',lat:16.1,lon:-22.8,status:'ExploraciÃ³n realizada en este destino.'},{name:'Leyte',lat:10.9,lon:124.8,status:'ProspecciÃ³n programada para octubre de 2026.'},{name:'Addu Atoll',lat:-.63,lon:73.16,status:'ProspecciÃ³n programada para noviembre de 2026.'}];
let rotation=55,tilt=12,selected=0,drag=null,auto=!matchMedia('(prefers-reduced-motion: reduce)').matches,w=0,h=0,last=0,visible=true;
const rotate=document.querySelector('#rotate');
function setAuto(value){auto=value;rotate.textContent=auto?'â…¡ Pausar rotaciÃ³n':'â–· Activar rotaciÃ³n';rotate.setAttribute('aria-pressed',String(auto));}setAuto(auto);
function resize(){const b=canvas.getBoundingClientRect();w=b.width;h=b.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);}new ResizeObserver(resize).observe(canvas);
const rad=Math.PI/180;
function project(lon,lat){const l=(lon-rotation)*rad,p=lat*rad,t=tilt*rad,r=Math.min(w*.43,h*.43);const x=Math.cos(p)*Math.sin(l),y=Math.sin(p)*Math.cos(t)-Math.cos(p)*Math.cos(l)*Math.sin(t),z=Math.sin(p)*Math.sin(t)+Math.cos(p)*Math.cos(l)*Math.cos(t);return [w/2+r*x,h/2-r*y,z];}
function line(points,color,width=1){ctx.beginPath();let pen=false;for(const c of points){const p=project(c[0],c[1]);if(p[2]>0){if(pen)ctx.lineTo(p[0],p[1]);else ctx.moveTo(p[0],p[1]);pen=true;}else pen=false;}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function draw(ts){const dt=Math.min(ts-last,50);last=ts;if(visible&&w){if(auto&&!drag)rotation+=dt*.002;ctx.clearRect(0,0,w,h);const r=Math.min(w*.43,h*.43),cx=w/2,cy=h/2;const aura=ctx.createRadialGradient(cx,cy,r*.75,cx,cy,r*1.16);aura.addColorStop(0,'#1c678518');aura.addColorStop(.8,'#23729520');aura.addColorStop(1,'#08141e00');ctx.fillStyle=aura;ctx.fillRect(0,0,w,h);const ocean=ctx.createRadialGradient(cx-r*.4,cy-r*.4,0,cx,cy,r);ocean.addColorStop(0,'#113349');ocean.addColorStop(.8,'#091f30');ocean.addColorStop(1,'#05111d');ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle=ocean;ctx.fill();ctx.strokeStyle='#34758b';ctx.lineWidth=1;ctx.stroke();for(let lat=-60;lat<=60;lat+=30){const points=[];for(let lon=-180;lon<=180;lon+=3)points.push([lon,lat]);line(points,'#459bb526');}for(let lon=-180;lon<180;lon+=30){const points=[];for(let lat=-90;lat<=90;lat+=3)points.push([lon,lat]);line(points,'#459bb526');}for(const ring of window.WORLD_RINGS||[])line(ring,'#67b3c6a0',.75);places.forEach((place,i)=>{const p=project(place.lon,place.lat);if(p[2]<0)return;const col=i<2?'#62dbef':'#e2b976';ctx.beginPath();ctx.arc(p[0],p[1],i===selected?12:7,0,Math.PI*2);ctx.strokeStyle=col;ctx.lineWidth=i===selected?1.5:1;ctx.stroke();ctx.beginPath();ctx.arc(p[0],p[1],3,0,Math.PI*2);ctx.fillStyle=col;ctx.fill();if(i===selected){ctx.font='12px "DM Sans", sans-serif';ctx.textAlign=p[0]>w*.7?'right':'left';const tx=p[0]+(p[0]>w*.7?-18:18);ctx.fillStyle='#06121de6';const tw=ctx.measureText(place.name).width;ctx.fillRect(ctx.textAlign==='right'?tx-tw-5:tx-5,p[1]-29,tw+10,22);ctx.fillStyle='#e8f6fa';ctx.fillText(place.name,tx,p[1]-14);}});}requestAnimationFrame(draw);}requestAnimationFrame(draw);
new IntersectionObserver(entries=>visible=entries[0].isIntersecting).observe(canvas);
function selectPlace(i){selected=i;rotation=places[i].lon;tilt=places[i].lat;setAuto(false);document.querySelectorAll('.destination').forEach((b,j)=>{b.classList.toggle('selected',i===j);b.setAttribute('aria-pressed',String(i===j));});document.querySelector('#place-detail').textContent=places[i].name.toUpperCase()+' / '+places[i].status;}
document.querySelectorAll('.destination').forEach((button,i)=>{button.setAttribute('aria-pressed',String(i===selected));button.addEventListener('click',()=>selectPlace(i));});
rotate.addEventListener('click',()=>setAuto(!auto));
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};canvas.setPointerCapture(e.pointerId);setAuto(false);});
canvas.addEventListener('pointermove',e=>{if(!drag)return;rotation-=(e.clientX-drag.x)*.35;tilt=Math.max(-65,Math.min(65,tilt+(e.clientY-drag.y)*.3));drag.x=e.clientX;drag.y=e.clientY;});
canvas.addEventListener('pointerup',e=>{if(drag&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<5){const b=canvas.getBoundingClientRect();let closest=-1,distance=22;places.forEach((p,i)=>{const point=project(p.lon,p.lat),d=Math.hypot(point[0]-(e.clientX-b.left),point[1]-(e.clientY-b.top));if(point[2]>0&&d<distance){closest=i;distance=d;}});if(closest>=0)selectPlace(closest);}drag=null;});canvas.addEventListener('pointercancel',()=>drag=null);
canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();setAuto(false);if(e.key==='ArrowLeft')rotation-=10;if(e.key==='ArrowRight')rotation+=10;if(e.key==='ArrowUp')tilt=Math.min(65,tilt+10);if(e.key==='ArrowDown')tilt=Math.max(-65,tilt-10);});
document.querySelectorAll('details').forEach(detail=>detail.addEventListener('toggle',()=>{if(detail.open)document.querySelectorAll('details').forEach(other=>{if(other!==detail)other.open=false;});}));

